# Server Port
server.port=8000

# Profile
spring.profiles.active=prod

# Logging
logging.level.org.springframework.security=DEBUG

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix= classpath:/templates/
spring.thymeleaf.suffix= .html

spring.devtools.livereload.enabled=false

############################################################################################################
# PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root

# H2 Database
#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true
#spring.datasource.url=jdbc:h2:mem:htcturkiye
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# For initialize data with data.sql
spring.jpa.defer-datasource-initialization = true
spring.sql.init.mode = always
############################################################################################################

# Mail Host
spring.mail.host=mail.kodlacoz.com
spring.mail.port=587
spring.mail.username=iletisim@kodlacoz.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# enable actuator endpoints
management.endpoints.web.exposure.include=*

# Multipart file properties
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
